  
name: 'Development Pipeline'

on:
  push:

  pull_request:
    types: [opened, labeled] #, assigned]

# runs-on: ${{ matrix.os }}
# strategy:
#   matrix:
#     os: [macOS-10.14, ubuntu-18.04]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rafmudaf/openfast-ubuntu:dev
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive

      # - name: Get latest CMake
      #   uses: lukka/get-cmake@v3.17.3
      - name: Configure CMake & Compile Common Modules
        # if: github.event_name == 'commit' || contains( github.event.pull_request.labels.*.name, 'Action Test All')
        uses: lukka/run-cmake@v2.5
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeBuildType: RelWithDebInfo
          cmakeGenerator: UnixMakefiles # default is Ninja - Ninja 1.10 doesnt support Fortran
          cmakeAppendedArgs: -DBUILD_TESTING=ON
          buildDirectory: "${{ github.workspace }}/build"
          buildWithCMake: false
          # buildWithCMakeArgs: "--parallel 4 --target nwtclibs"  #

      - name: Compile Unit Tests
        uses: ./.github/actions/compile
        with:
          build-target: 'unit_tests'
      - name: Compile Drivers
        uses: ./.github/actions/compile
        with:
          build-target: 'beamdyn_driver hydrodyn_driver'
      - name: Compile OpenFAST
        if: contains( github.event.pull_request.labels.*.name, 'Action Test All')
        uses: ./.github/actions/compile
        with:
          build-target: 'install'

      - name: 'NWTC Library tests'
        uses: ./.github/actions/tests-module-nwtclibrary
      - name: 'Run AeroDyn tests'
        uses: ./.github/actions/tests-module-aerodyn
      - name: 'Run BeamDyn tests'
        uses: ./.github/actions/tests-module-beamdyn
      - name: 'Run OpenFAST tests'
        if: contains( github.event.pull_request.labels.*.name, 'Action Test All')
        uses: ./.github/actions/tests-gluecode-openfast
