
name: 'Docker Pipeline'

on:
  release:
    types: [published]

  pull_request:
    types: [labeled]

jobs:
  build-and-push:

    # Do not run if:
    # - Branch name contains "docs/"
    if: "!contains( github.ref, 'docs/')"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        if: contains( github.event.pull_request.labels.*.name, 'Update Docker')
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./share/docker/openfast_ubuntu/Dockerfile
          push: true
          tags: rafmudaf/openfast:dev
